version: 0.0.1
mongohost: localhost
mongoport: 27017
mongodb: Administration
requestCollection: Requests
streamCollection: Streams

# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 9000
  - type: https
    port: 9001
    keyStorePath: GdoTwit.keystore
    keyStorePassword: gdotwitter
    validateCerts: false
  adminConnectors:
  - type: http
    port: 9002

logging:
  level: ALL
  appenders:
    - type: file
      currentLogFilename: log/status.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: log/status-%d.log
      archivedFileCount: 5
      timeZone: UTC
    - type: console
      threshold: WARNING
      timeZone: UTC
      target: stdout