version: 0.0.1
mongohost: localhost
mongoport: 27017
mongodb: Administration
requestCollection: Requests
streamCollection: Streams
analyticsCollection: Analytics

consumerKey : uxMqOuKT66k0ihHJ9aQRoCq2x
consumerSecret : zyc5BC1voOMPmJs3G7o1hHv4jI8ii6WGctf4yzdg43xQzxPH0U
accessKey : 529742116-XJ1FPnd2ANhx8UDsv3espl1OAlufhzQT5G6yQDxA
accessSecret : sHoqlokqwo0OPz2RRBjxBL3E8CKszf9dibi8ao4xLykMS

# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 9000
  - type: https
    port: 9001
    keyStorePath: GdoTwit.keystore
    keyStorePassword: gdotwitter
    validateCerts: false
  adminConnectors:
  - type: http
    port: 9002

logging:
  level: INFO
  loggers:
    com.cps15.service.DataService.TwitterStreamCollector: INFO
  appenders:
    - type: file
      currentLogFilename: log/application.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: log/application-%i.log.gz
      archivedFileCount: 5
      timeZone: UTC
      maxFileSize: 10MB
    - type: console
      threshold: WARNING
      timeZone: UTC
      target: stdout