version: 0.0.1
mongohost: localhost
mongoport: 27017
mongodb: Administration
requestCollection: Requests
streamCollection: Streams

# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 9000
  - type: https
    port: 9001
    keyStorePath: GdoTwit.keystore
    keyStorePassword: gdotwitter
    validateCerts: false
  adminConnectors:
  - type: http
    port: 9002

logging:
  level: INFO
  loggers:
    com.cps15.service.DataService.TwitterStreamCollector: DEBUG
  appenders:
    - type: file
      currentLogFilename: log/application.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: log/application-%i.log.gz
      archivedFileCount: 5
      timeZone: UTC
      maxFileSize: 10MB
    - type: console
      threshold: WARNING
      timeZone: UTC
      target: stdout